/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AuthUsers: () => import('#controllers/auth_users_controller'),
  Countries: () => import('#controllers/countries_controller'),
  FavouriteLeagues: () => import('#controllers/favourite_leagues_controller'),
  Games: () => import('#controllers/games_controller'),
  Invites: () => import('#controllers/invites_controller'),
  LeaguePlayers: () => import('#controllers/league_players_controller'),
  Leagues: () => import('#controllers/leagues_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Players: () => import('#controllers/players_controller'),
  Searches: () => import('#controllers/searches_controller'),
  Seasons: () => import('#controllers/seasons_controller'),
  Session: () => import('#controllers/session_controller'),
  Stats: () => import('#controllers/stats_controller'),
  Teams: () => import('#controllers/teams_controller'),
  Users: () => import('#controllers/users_controller'),
}
