/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdminAuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorId', 'createdAt', 'entityId', 'entityType', 'id', 'ipAddress', 'leagueId', 'metadata'] as const
  $columns = AdminAuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: bigint | number | null
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare leagueId: number
  @column()
  declare metadata: any
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CountrySchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'flagUrl', 'id', 'name', 'updatedAt'] as const
  $columns = CountrySchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare flagUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FavouriteLeagueSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'leagueId', 'updatedAt', 'userId'] as const
  $columns = FavouriteLeagueSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leagueId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class FormationSchema extends BaseModel {
  static $columns = ['createdAt', 'displayName', 'id', 'isActive', 'name', 'slots'] as const
  $columns = FormationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare displayName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column()
  declare slots: any
}

export class GameLineupSchema extends BaseModel {
  static $columns = ['createdAt', 'formationId', 'gameId', 'id', 'jerseyNumber', 'playerId', 'position', 'slotKey', 'startingOrder', 'status', 'subbedInMinute', 'subbedOutMinute', 'teamId', 'updatedAt'] as const
  $columns = GameLineupSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare formationId: number | null
  @column()
  declare gameId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare jerseyNumber: number | null
  @column()
  declare playerId: number
  @column()
  declare position: string | null
  @column()
  declare slotKey: string | null
  @column()
  declare startingOrder: number | null
  @column()
  declare status: string | null
  @column()
  declare subbedInMinute: number | null
  @column()
  declare subbedOutMinute: number | null
  @column()
  declare teamId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GameSchema extends BaseModel {
  static $columns = ['awayPenaltyScore', 'awayScore', 'awayTeamId', 'bracketPosition', 'createdAt', 'currentMinute', 'extraTimeDuration', 'extraTimeStartedAt', 'firstHalfDuration', 'firstHalfStartedAt', 'homePenaltyScore', 'homeScore', 'homeTeamId', 'id', 'leagueId', 'leg', 'pausedAt', 'pausedFromStatus', 'playedAt', 'round', 'seasonId', 'secondHalfDuration', 'secondHalfStartedAt', 'stageGroupId', 'stageId', 'status', 'tieId', 'updatedAt', 'venueId', 'venueName', 'winnerTeamId'] as const
  $columns = GameSchema.$columns
  @column()
  declare awayPenaltyScore: number | null
  @column()
  declare awayScore: number | null
  @column()
  declare awayTeamId: number
  @column()
  declare bracketPosition: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currentMinute: number | null
  @column()
  declare extraTimeDuration: number | null
  @column.dateTime()
  declare extraTimeStartedAt: DateTime | null
  @column()
  declare firstHalfDuration: number
  @column.dateTime()
  declare firstHalfStartedAt: DateTime | null
  @column()
  declare homePenaltyScore: number | null
  @column()
  declare homeScore: number | null
  @column()
  declare homeTeamId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leagueId: number
  @column()
  declare leg: number | null
  @column.dateTime()
  declare pausedAt: DateTime | null
  @column()
  declare pausedFromStatus: string | null
  @column.dateTime()
  declare playedAt: DateTime
  @column()
  declare round: string | null
  @column()
  declare seasonId: number
  @column()
  declare secondHalfDuration: number
  @column.dateTime()
  declare secondHalfStartedAt: DateTime | null
  @column()
  declare stageGroupId: number | null
  @column()
  declare stageId: number | null
  @column()
  declare status: string | null
  @column()
  declare tieId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare venueId: number | null
  @column()
  declare venueName: string | null
  @column()
  declare winnerTeamId: number | null
}

export class IdempotencyKeySchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'keyHash', 'method', 'path', 'requestHash', 'responseBody', 'responseHeaders', 'responseStatus', 'status', 'updatedAt', 'userId'] as const
  $columns = IdempotencyKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare keyHash: string
  @column()
  declare method: string
  @column()
  declare path: string
  @column()
  declare requestHash: string
  @column()
  declare responseBody: any | null
  @column()
  declare responseHeaders: any | null
  @column()
  declare responseStatus: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class InviteSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'expiresAt', 'id', 'invitedUserId', 'leagueId', 'seasonId', 'status', 'teamId', 'token', 'updatedAt'] as const
  $columns = InviteSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedUserId: number | null
  @column()
  declare leagueId: number | null
  @column()
  declare seasonId: number
  @column()
  declare status: string | null
  @column()
  declare teamId: number | null
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LeagueNotificationPreferenceSchema extends BaseModel {
  static $columns = ['createdAt', 'enabled', 'finalScoreEnabled', 'id', 'kickoffEnabled', 'leagueId', 'updatedAt', 'userId'] as const
  $columns = LeagueNotificationPreferenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare enabled: boolean
  @column()
  declare finalScoreEnabled: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kickoffEnabled: boolean
  @column()
  declare leagueId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class LeaguePlayerSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isCaptain', 'jerseyNumber', 'joinedAt', 'leagueId', 'leftAt', 'playerId', 'position', 'seasonId', 'status', 'teamId', 'updatedAt'] as const
  $columns = LeaguePlayerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCaptain: boolean | null
  @column()
  declare jerseyNumber: string | null
  @column.dateTime()
  declare joinedAt: DateTime | null
  @column()
  declare leagueId: number
  @column.dateTime()
  declare leftAt: DateTime | null
  @column()
  declare playerId: number
  @column()
  declare position: string | null
  @column()
  declare seasonId: number
  @column()
  declare status: string | null
  @column()
  declare teamId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LeagueSchema extends BaseModel {
  static $columns = ['countryId', 'createdAt', 'description', 'endDate', 'gender', 'id', 'logoUrl', 'name', 'startDate', 'tiebreaker', 'updatedAt', 'userId'] as const
  $columns = LeagueSchema.$columns
  @column()
  declare countryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column.date()
  declare endDate: DateTime | null
  @column()
  declare gender: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string
  @column.date()
  declare startDate: DateTime | null
  @column()
  declare tiebreaker: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class OtpCodeSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'email', 'expiresAt', 'id', 'isUsed', 'updatedAt', 'userId'] as const
  $columns = OtpCodeSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isUsed: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class PasswordResetSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'tokenHash', 'updatedAt', 'userId'] as const
  $columns = PasswordResetSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PlayerAwardSchema extends BaseModel {
  static $columns = ['awardType', 'awardedBy', 'createdAt', 'gameId', 'id', 'playerId', 'updatedAt'] as const
  $columns = PlayerAwardSchema.$columns
  @column()
  declare awardType: string
  @column()
  declare awardedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gameId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare playerId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PlayerHighlightSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'playerId', 'sortOrder', 'title', 'updatedAt', 'videoId'] as const
  $columns = PlayerHighlightSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare playerId: number
  @column()
  declare sortOrder: number
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare videoId: string
}

export class PlayerSchema extends BaseModel {
  static $columns = ['addedBy', 'avatarUrl', 'bio', 'city', 'countryId', 'createdAt', 'dateOfBirth', 'heightCm', 'id', 'name', 'nationality', 'preferredFoot', 'primaryPosition', 'secondaryPosition', 'socialHandle', 'state', 'updatedAt', 'userId', 'visibility'] as const
  $columns = PlayerSchema.$columns
  @column()
  declare addedBy: number | null
  @column()
  declare avatarUrl: string | null
  @column()
  declare bio: string | null
  @column()
  declare city: string | null
  @column()
  declare countryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare dateOfBirth: DateTime | null
  @column()
  declare heightCm: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column()
  declare nationality: string | null
  @column()
  declare preferredFoot: string | null
  @column()
  declare primaryPosition: string | null
  @column()
  declare secondaryPosition: string | null
  @column()
  declare socialHandle: string | null
  @column()
  declare state: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare visibility: string
}

export class SeasonSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'leagueId', 'name', 'status', 'updatedAt'] as const
  $columns = SeasonSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leagueId: number
  @column()
  declare name: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StageGroupSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'sequence', 'stageId', 'updatedAt'] as const
  $columns = StageGroupSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare sequence: number
  @column()
  declare stageId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StageTeamSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'seed', 'stageGroupId', 'stageId', 'teamId', 'updatedAt'] as const
  $columns = StageTeamSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare seed: number | null
  @column()
  declare stageGroupId: number | null
  @column()
  declare stageId: number
  @column()
  declare teamId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StageSchema extends BaseModel {
  static $columns = ['config', 'createdAt', 'id', 'name', 'seasonId', 'sequence', 'sourceStageId', 'stageType', 'status', 'updatedAt'] as const
  $columns = StageSchema.$columns
  @column()
  declare config: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare seasonId: number
  @column()
  declare sequence: number
  @column()
  declare sourceStageId: number | null
  @column()
  declare stageType: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StandingAdjustmentSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'id', 'pointsDelta', 'reason', 'stageGroupId', 'stageId', 'teamId', 'updatedAt'] as const
  $columns = StandingAdjustmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pointsDelta: number
  @column()
  declare reason: string
  @column()
  declare stageGroupId: number | null
  @column()
  declare stageId: number
  @column()
  declare teamId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StandingOverrideSchema extends BaseModel {
  static $columns = ['cohortSignature', 'createdAt', 'createdBy', 'id', 'manualRank', 'reason', 'stageGroupId', 'stageId', 'teamId', 'updatedAt'] as const
  $columns = StandingOverrideSchema.$columns
  @column()
  declare cohortSignature: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare manualRank: number
  @column()
  declare reason: string | null
  @column()
  declare stageGroupId: number | null
  @column()
  declare stageId: number
  @column()
  declare teamId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StandingZoneSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'label', 'positionEnd', 'positionStart', 'stageGroupId', 'stageId', 'updatedAt', 'zoneType'] as const
  $columns = StandingZoneSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string | null
  @column()
  declare positionEnd: number
  @column()
  declare positionStart: number
  @column()
  declare stageGroupId: number | null
  @column()
  declare stageId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare zoneType: string
}

export class StandingSchema extends BaseModel {
  static $columns = ['createdAt', 'draws', 'form', 'goalDifference', 'goalsAgainst', 'goalsFor', 'id', 'leagueId', 'losses', 'played', 'points', 'position', 'seasonId', 'stageGroupId', 'stageId', 'teamId', 'updatedAt', 'wins'] as const
  $columns = StandingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare draws: number | null
  @column()
  declare form: string | null
  @column()
  declare goalDifference: number | null
  @column()
  declare goalsAgainst: number | null
  @column()
  declare goalsFor: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leagueId: number
  @column()
  declare losses: number | null
  @column()
  declare played: number | null
  @column()
  declare points: number | null
  @column()
  declare position: number | null
  @column()
  declare seasonId: number
  @column()
  declare stageGroupId: number | null
  @column()
  declare stageId: number | null
  @column()
  declare teamId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wins: number | null
}

export class StatTypeSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'displayName', 'iconName', 'id', 'name', 'updatedAt'] as const
  $columns = StatTypeSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare displayName: string
  @column()
  declare iconName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StatSchema extends BaseModel {
  static $columns = ['clientEventId', 'createdAt', 'gameId', 'id', 'isPenalty', 'isStoppageTime', 'leagueId', 'minute', 'numericValue', 'playerId', 'qualifiers', 'relatedPlayerId', 'seasonId', 'statTypeId', 'teamId', 'updatedAt', 'value'] as const
  $columns = StatSchema.$columns
  @column()
  declare clientEventId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gameId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPenalty: boolean
  @column()
  declare isStoppageTime: boolean | null
  @column()
  declare leagueId: number
  @column()
  declare minute: number | null
  @column()
  declare numericValue: number | null
  @column()
  declare playerId: number | null
  @column()
  declare qualifiers: any
  @column()
  declare relatedPlayerId: number | null
  @column()
  declare seasonId: number
  @column()
  declare statTypeId: number
  @column()
  declare teamId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class TeamAdminSchema extends BaseModel {
  static $columns = ['assignedBy', 'createdAt', 'id', 'leagueId', 'removedAt', 'teamId', 'updatedAt', 'userId'] as const
  $columns = TeamAdminSchema.$columns
  @column()
  declare assignedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leagueId: number
  @column.dateTime()
  declare removedAt: DateTime | null
  @column()
  declare teamId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TeamSchema extends BaseModel {
  static $columns = ['addedBy', 'createdAt', 'id', 'leagueId', 'logoUrl', 'name', 'updatedAt'] as const
  $columns = TeamSchema.$columns
  @column()
  declare addedBy: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leagueId: number
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TieSchema extends BaseModel {
  static $columns = ['awayGoals', 'awayScoreAgg', 'awayTeamId', 'bestOf', 'bracketPosition', 'createdAt', 'homeScoreAgg', 'homeTeamId', 'id', 'isBye', 'round', 'stageId', 'status', 'targetWins', 'tieFormat', 'updatedAt', 'winnerTeamId'] as const
  $columns = TieSchema.$columns
  @column()
  declare awayGoals: boolean
  @column()
  declare awayScoreAgg: number | null
  @column()
  declare awayTeamId: number | null
  @column()
  declare bestOf: number | null
  @column()
  declare bracketPosition: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare homeScoreAgg: number | null
  @column()
  declare homeTeamId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isBye: boolean
  @column()
  declare round: string
  @column()
  declare stageId: number
  @column()
  declare status: string
  @column()
  declare targetWins: number | null
  @column()
  declare tieFormat: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare winnerTeamId: number | null
}

export class UserPushTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'deviceId', 'disabledAt', 'id', 'lastSeenAt', 'platform', 'provider', 'token', 'updatedAt', 'userId'] as const
  $columns = UserPushTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare deviceId: string | null
  @column.dateTime()
  declare disabledAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastSeenAt: DateTime
  @column()
  declare platform: string | null
  @column()
  declare provider: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'phone', 'recoveryEmail', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare phone: string | null
  @column()
  declare recoveryEmail: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VenueSchema extends BaseModel {
  static $columns = ['address', 'capacity', 'city', 'createdAt', 'createdBy', 'googlePlaceId', 'id', 'latitude', 'leagueId', 'longitude', 'name', 'notes', 'updatedAt'] as const
  $columns = VenueSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare capacity: number | null
  @column()
  declare city: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: number | null
  @column()
  declare googlePlaceId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: string | null
  @column()
  declare leagueId: number
  @column()
  declare longitude: string | null
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
