/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CountrySchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'flagUrl', 'id', 'name', 'updatedAt'] as const
  $columns = CountrySchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare flagUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FavouriteLeagueSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'leagueId', 'updatedAt', 'userId'] as const
  $columns = FavouriteLeagueSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leagueId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class GameSchema extends BaseModel {
  static $columns = ['awayScore', 'awayTeamId', 'createdAt', 'currentMinute', 'extraTimeDuration', 'extraTimeStartedAt', 'firstHalfDuration', 'firstHalfStartedAt', 'homeScore', 'homeTeamId', 'id', 'leagueId', 'pausedAt', 'pausedFromStatus', 'playedAt', 'seasonId', 'secondHalfDuration', 'secondHalfStartedAt', 'status', 'updatedAt', 'venueName'] as const
  $columns = GameSchema.$columns
  @column()
  declare awayScore: number | null
  @column()
  declare awayTeamId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currentMinute: number | null
  @column()
  declare extraTimeDuration: number | null
  @column.dateTime()
  declare extraTimeStartedAt: DateTime | null
  @column()
  declare firstHalfDuration: number
  @column.dateTime()
  declare firstHalfStartedAt: DateTime | null
  @column()
  declare homeScore: number | null
  @column()
  declare homeTeamId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leagueId: number
  @column.dateTime()
  declare pausedAt: DateTime | null
  @column()
  declare pausedFromStatus: string | null
  @column.dateTime()
  declare playedAt: DateTime
  @column()
  declare seasonId: number
  @column()
  declare secondHalfDuration: number
  @column.dateTime()
  declare secondHalfStartedAt: DateTime | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare venueName: string | null
}

export class InviteSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'expiresAt', 'id', 'invitedUserId', 'leagueId', 'seasonId', 'status', 'teamId', 'token', 'updatedAt'] as const
  $columns = InviteSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedUserId: number | null
  @column()
  declare leagueId: number | null
  @column()
  declare seasonId: number
  @column()
  declare status: string | null
  @column()
  declare teamId: number | null
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LeaguePlayerSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isCaptain', 'jerseyNumber', 'joinedAt', 'leagueId', 'leftAt', 'playerId', 'position', 'seasonId', 'status', 'teamId', 'updatedAt'] as const
  $columns = LeaguePlayerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCaptain: boolean | null
  @column()
  declare jerseyNumber: string | null
  @column.dateTime()
  declare joinedAt: DateTime | null
  @column()
  declare leagueId: number
  @column.dateTime()
  declare leftAt: DateTime | null
  @column()
  declare playerId: number
  @column()
  declare position: string | null
  @column()
  declare seasonId: number
  @column()
  declare status: string | null
  @column()
  declare teamId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LeagueSchema extends BaseModel {
  static $columns = ['countryId', 'createdAt', 'description', 'gender', 'id', 'logoUrl', 'name', 'tiebreaker', 'updatedAt', 'userId'] as const
  $columns = LeagueSchema.$columns
  @column()
  declare countryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare gender: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string
  @column()
  declare tiebreaker: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class OtpCodeSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'email', 'expiresAt', 'id', 'isUsed', 'updatedAt', 'userId'] as const
  $columns = OtpCodeSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isUsed: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class PasswordResetSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'tokenHash', 'updatedAt', 'userId'] as const
  $columns = PasswordResetSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PlayerSchema extends BaseModel {
  static $columns = ['addedBy', 'avatarUrl', 'bio', 'countryId', 'createdAt', 'id', 'name', 'updatedAt', 'userId'] as const
  $columns = PlayerSchema.$columns
  @column()
  declare addedBy: number | null
  @column()
  declare avatarUrl: string | null
  @column()
  declare bio: string | null
  @column()
  declare countryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SeasonSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'leagueId', 'name', 'status', 'updatedAt'] as const
  $columns = SeasonSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leagueId: number
  @column()
  declare name: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StandingSchema extends BaseModel {
  static $columns = ['createdAt', 'draws', 'form', 'goalDifference', 'goalsAgainst', 'goalsFor', 'id', 'leagueId', 'losses', 'played', 'points', 'position', 'seasonId', 'teamId', 'updatedAt', 'wins'] as const
  $columns = StandingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare draws: number | null
  @column()
  declare form: string | null
  @column()
  declare goalDifference: number | null
  @column()
  declare goalsAgainst: number | null
  @column()
  declare goalsFor: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leagueId: number
  @column()
  declare losses: number | null
  @column()
  declare played: number | null
  @column()
  declare points: number | null
  @column()
  declare position: number | null
  @column()
  declare seasonId: number
  @column()
  declare teamId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wins: number | null
}

export class StatTypeSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'displayName', 'iconName', 'id', 'name', 'updatedAt'] as const
  $columns = StatTypeSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare displayName: string
  @column()
  declare iconName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StatSchema extends BaseModel {
  static $columns = ['createdAt', 'gameId', 'id', 'isStoppageTime', 'leagueId', 'minute', 'numericValue', 'playerId', 'relatedPlayerId', 'seasonId', 'statTypeId', 'teamId', 'updatedAt', 'value'] as const
  $columns = StatSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gameId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isStoppageTime: boolean | null
  @column()
  declare leagueId: number
  @column()
  declare minute: number | null
  @column()
  declare numericValue: number | null
  @column()
  declare playerId: number | null
  @column()
  declare relatedPlayerId: number | null
  @column()
  declare seasonId: number
  @column()
  declare statTypeId: number
  @column()
  declare teamId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class TeamSchema extends BaseModel {
  static $columns = ['addedBy', 'createdAt', 'id', 'leagueId', 'logoUrl', 'name', 'updatedAt'] as const
  $columns = TeamSchema.$columns
  @column()
  declare addedBy: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare leagueId: number
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'phone', 'recoveryEmail', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare phone: string | null
  @column()
  declare recoveryEmail: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
