/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type AuthSessionTransformer from '#transformers/auth_session_transformer'
import type CountryDetailTransformer from '#transformers/country_detail_transformer'
import type CountryTransformer from '#transformers/country_transformer'
import type GameTransformer from '#transformers/game_transformer'
import type LeaguePlayerTransformer from '#transformers/league_player_transformer'
import type LeagueTransformer from '#transformers/league_transformer'
import type OwnedLeagueTransformer from '#transformers/owned_league_transformer'
import type PlayerLeagueDetailTransformer from '#transformers/player_league_detail_transformer'
import type PlayerSeasonDetailTransformer from '#transformers/player_season_detail_transformer'
import type PlayerTransformer from '#transformers/player_transformer'
import type SearchTransformer from '#transformers/search_transformer'
import type SeasonTransformer from '#transformers/season_transformer'
import type StandingTransformer from '#transformers/standing_transformer'
import type StatTransformer from '#transformers/stat_transformer'
import type StatsTypeTransformer from '#transformers/stats_type_transformer'
import type TeamLeagueDetailTransformer from '#transformers/team_league_detail_transformer'
import type TeamSeasonDetailTransformer from '#transformers/team_season_detail_transformer'
import type TeamTransformer from '#transformers/team_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type AuthSession = InferData<AuthSessionTransformer>
  export namespace AuthSession {
    export type Variants = InferVariants<AuthSessionTransformer>
  }
  export type CountryDetail = InferData<CountryDetailTransformer>
  export namespace CountryDetail {
    export type Variants = InferVariants<CountryDetailTransformer>
  }
  export type Country = InferData<CountryTransformer>
  export namespace Country {
    export type Variants = InferVariants<CountryTransformer>
  }
  export type Game = InferData<GameTransformer>
  export namespace Game {
    export type Variants = InferVariants<GameTransformer>
  }
  export type LeaguePlayer = InferData<LeaguePlayerTransformer>
  export namespace LeaguePlayer {
    export type Variants = InferVariants<LeaguePlayerTransformer>
  }
  export type League = InferData<LeagueTransformer>
  export namespace League {
    export type Variants = InferVariants<LeagueTransformer>
  }
  export type OwnedLeague = InferData<OwnedLeagueTransformer>
  export namespace OwnedLeague {
    export type Variants = InferVariants<OwnedLeagueTransformer>
  }
  export type PlayerLeagueDetail = InferData<PlayerLeagueDetailTransformer>
  export namespace PlayerLeagueDetail {
    export type Variants = InferVariants<PlayerLeagueDetailTransformer>
  }
  export type PlayerSeasonDetail = InferData<PlayerSeasonDetailTransformer>
  export namespace PlayerSeasonDetail {
    export type Variants = InferVariants<PlayerSeasonDetailTransformer>
  }
  export type Player = InferData<PlayerTransformer>
  export namespace Player {
    export type Variants = InferVariants<PlayerTransformer>
  }
  export type Search = InferData<SearchTransformer>
  export namespace Search {
    export type Variants = InferVariants<SearchTransformer>
  }
  export type Season = InferData<SeasonTransformer>
  export namespace Season {
    export type Variants = InferVariants<SeasonTransformer>
  }
  export type Standing = InferData<StandingTransformer>
  export namespace Standing {
    export type Variants = InferVariants<StandingTransformer>
  }
  export type Stat = InferData<StatTransformer>
  export namespace Stat {
    export type Variants = InferVariants<StatTransformer>
  }
  export type StatsType = InferData<StatsTypeTransformer>
  export namespace StatsType {
    export type Variants = InferVariants<StatsTypeTransformer>
  }
  export type TeamLeagueDetail = InferData<TeamLeagueDetailTransformer>
  export namespace TeamLeagueDetail {
    export type Variants = InferVariants<TeamLeagueDetailTransformer>
  }
  export type TeamSeasonDetail = InferData<TeamSeasonDetailTransformer>
  export namespace TeamSeasonDetail {
    export type Variants = InferVariants<TeamSeasonDetailTransformer>
  }
  export type Team = InferData<TeamTransformer>
  export namespace Team {
    export type Variants = InferVariants<TeamTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
