import { BaseSchema } from '@adonisjs/lucid/schema'
import { DateTime } from 'luxon'

export default class extends BaseSchema {
  protected tableName = 'countries'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.increments('id')
      table.string('name', 120).notNullable()
      table.string('code', 2).notNullable().unique()
      table.string('flag_url').nullable()
      table.timestamp('created_at')
      table.timestamp('updated_at')
    })

    this.defer(async (db) => {
      const now = DateTime.utc().toSQL({ includeOffset: false }) ?? DateTime.utc().toISO()
      await db.table(this.tableName).insert([
        { name: 'Andorra', code: 'ad', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'United Arab Emirates',
          code: 'ae',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Afghanistan', code: 'af', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Antigua and Barbuda',
          code: 'ag',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Anguilla', code: 'ai', flag_url: null, created_at: now, updated_at: now },
        { name: 'Albania', code: 'al', flag_url: null, created_at: now, updated_at: now },
        { name: 'Armenia', code: 'am', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Netherlands Antilles',
          code: 'an',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Angola', code: 'ao', flag_url: null, created_at: now, updated_at: now },
        { name: 'Antarctica', code: 'aq', flag_url: null, created_at: now, updated_at: now },
        { name: 'Argentina', code: 'ar', flag_url: null, created_at: now, updated_at: now },
        { name: 'American Samoa', code: 'as', flag_url: null, created_at: now, updated_at: now },
        { name: 'Austria', code: 'at', flag_url: null, created_at: now, updated_at: now },
        { name: 'Australia', code: 'au', flag_url: null, created_at: now, updated_at: now },
        { name: 'Aruba', code: 'aw', flag_url: null, created_at: now, updated_at: now },
        { name: 'Azerbaijan', code: 'az', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Bosnia and Herzegovina',
          code: 'ba',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Barbados', code: 'bb', flag_url: null, created_at: now, updated_at: now },
        { name: 'Bangladesh', code: 'bd', flag_url: null, created_at: now, updated_at: now },
        { name: 'Belgium', code: 'be', flag_url: null, created_at: now, updated_at: now },
        { name: 'Burkina Faso', code: 'bf', flag_url: null, created_at: now, updated_at: now },
        { name: 'Bulgaria', code: 'bg', flag_url: null, created_at: now, updated_at: now },
        { name: 'Bahrain', code: 'bh', flag_url: null, created_at: now, updated_at: now },
        { name: 'Burundi', code: 'bi', flag_url: null, created_at: now, updated_at: now },
        { name: 'Benin', code: 'bj', flag_url: null, created_at: now, updated_at: now },
        { name: 'Bermuda', code: 'bm', flag_url: null, created_at: now, updated_at: now },
        { name: 'Brunei', code: 'bn', flag_url: null, created_at: now, updated_at: now },
        { name: 'Bolivia', code: 'bo', flag_url: null, created_at: now, updated_at: now },
        { name: 'Brazil', code: 'br', flag_url: null, created_at: now, updated_at: now },
        { name: 'Bahamas', code: 'bs', flag_url: null, created_at: now, updated_at: now },
        { name: 'Bhutan', code: 'bt', flag_url: null, created_at: now, updated_at: now },
        { name: 'Bouvet Island', code: 'bv', flag_url: null, created_at: now, updated_at: now },
        { name: 'Botswana', code: 'bw', flag_url: null, created_at: now, updated_at: now },
        { name: 'Belarus', code: 'by', flag_url: null, created_at: now, updated_at: now },
        { name: 'Belize', code: 'bz', flag_url: null, created_at: now, updated_at: now },
        { name: 'Canada', code: 'ca', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Cocos [Keeling] Islands',
          code: 'cc',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Congo [DRC]', code: 'cd', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Central African Republic',
          code: 'cf',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Congo [Republic]', code: 'cg', flag_url: null, created_at: now, updated_at: now },
        { name: 'Switzerland', code: 'ch', flag_url: null, created_at: now, updated_at: now },
        { name: "Côte d'Ivoire", code: 'ci', flag_url: null, created_at: now, updated_at: now },
        { name: 'Cook Islands', code: 'ck', flag_url: null, created_at: now, updated_at: now },
        { name: 'Chile', code: 'cl', flag_url: null, created_at: now, updated_at: now },
        { name: 'Cameroon', code: 'cm', flag_url: null, created_at: now, updated_at: now },
        { name: 'China', code: 'cn', flag_url: null, created_at: now, updated_at: now },
        { name: 'Colombia', code: 'co', flag_url: null, created_at: now, updated_at: now },
        { name: 'Costa Rica', code: 'cr', flag_url: null, created_at: now, updated_at: now },
        { name: 'Cuba', code: 'cu', flag_url: null, created_at: now, updated_at: now },
        { name: 'Cape Verde', code: 'cv', flag_url: null, created_at: now, updated_at: now },
        { name: 'Christmas Island', code: 'cx', flag_url: null, created_at: now, updated_at: now },
        { name: 'Cyprus', code: 'cy', flag_url: null, created_at: now, updated_at: now },
        { name: 'Czech Republic', code: 'cz', flag_url: null, created_at: now, updated_at: now },
        { name: 'Germany', code: 'de', flag_url: null, created_at: now, updated_at: now },
        { name: 'Djibouti', code: 'dj', flag_url: null, created_at: now, updated_at: now },
        { name: 'Denmark', code: 'dk', flag_url: null, created_at: now, updated_at: now },
        { name: 'Dominica', code: 'dm', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Dominican Republic',
          code: 'do',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Algeria', code: 'dz', flag_url: null, created_at: now, updated_at: now },
        { name: 'Ecuador', code: 'ec', flag_url: null, created_at: now, updated_at: now },
        { name: 'Estonia', code: 'ee', flag_url: null, created_at: now, updated_at: now },
        { name: 'Egypt', code: 'eg', flag_url: null, created_at: now, updated_at: now },
        { name: 'Western Sahara', code: 'eh', flag_url: null, created_at: now, updated_at: now },
        { name: 'Eritrea', code: 'er', flag_url: null, created_at: now, updated_at: now },
        { name: 'Spain', code: 'es', flag_url: null, created_at: now, updated_at: now },
        { name: 'Ethiopia', code: 'et', flag_url: null, created_at: now, updated_at: now },
        { name: 'Finland', code: 'fi', flag_url: null, created_at: now, updated_at: now },
        { name: 'Fiji', code: 'fj', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Falkland Islands [Islas Malvinas]',
          code: 'fk',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Micronesia', code: 'fm', flag_url: null, created_at: now, updated_at: now },
        { name: 'Faroe Islands', code: 'fo', flag_url: null, created_at: now, updated_at: now },
        { name: 'France', code: 'fr', flag_url: null, created_at: now, updated_at: now },
        { name: 'Gabon', code: 'ga', flag_url: null, created_at: now, updated_at: now },
        { name: 'United Kingdom', code: 'gb', flag_url: null, created_at: now, updated_at: now },
        { name: 'Grenada', code: 'gd', flag_url: null, created_at: now, updated_at: now },
        { name: 'Georgia', code: 'ge', flag_url: null, created_at: now, updated_at: now },
        { name: 'French Guiana', code: 'gf', flag_url: null, created_at: now, updated_at: now },
        { name: 'Guernsey', code: 'gg', flag_url: null, created_at: now, updated_at: now },
        { name: 'Ghana', code: 'gh', flag_url: null, created_at: now, updated_at: now },
        { name: 'Gibraltar', code: 'gi', flag_url: null, created_at: now, updated_at: now },
        { name: 'Greenland', code: 'gl', flag_url: null, created_at: now, updated_at: now },
        { name: 'Gambia', code: 'gm', flag_url: null, created_at: now, updated_at: now },
        { name: 'Guinea', code: 'gn', flag_url: null, created_at: now, updated_at: now },
        { name: 'Guadeloupe', code: 'gp', flag_url: null, created_at: now, updated_at: now },
        { name: 'Equatorial Guinea', code: 'gq', flag_url: null, created_at: now, updated_at: now },
        { name: 'Greece', code: 'gr', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'South Georgia and the South Sandwich Islands',
          code: 'gs',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Guatemala', code: 'gt', flag_url: null, created_at: now, updated_at: now },
        { name: 'Guam', code: 'gu', flag_url: null, created_at: now, updated_at: now },
        { name: 'Guinea-Bissau', code: 'gw', flag_url: null, created_at: now, updated_at: now },
        { name: 'Guyana', code: 'gy', flag_url: null, created_at: now, updated_at: now },
        { name: 'Gaza Strip', code: 'gz', flag_url: null, created_at: now, updated_at: now },
        { name: 'Hong Kong', code: 'hk', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Heard Island and McDonald Islands',
          code: 'hm',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Honduras', code: 'hn', flag_url: null, created_at: now, updated_at: now },
        { name: 'Croatia', code: 'hr', flag_url: null, created_at: now, updated_at: now },
        { name: 'Haiti', code: 'ht', flag_url: null, created_at: now, updated_at: now },
        { name: 'Hungary', code: 'hu', flag_url: null, created_at: now, updated_at: now },
        { name: 'Indonesia', code: 'id', flag_url: null, created_at: now, updated_at: now },
        { name: 'Ireland', code: 'ie', flag_url: null, created_at: now, updated_at: now },
        { name: 'Israel', code: 'il', flag_url: null, created_at: now, updated_at: now },
        { name: 'Isle of Man', code: 'im', flag_url: null, created_at: now, updated_at: now },
        { name: 'India', code: 'in', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'British Indian Ocean Territory',
          code: 'io',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Iraq', code: 'iq', flag_url: null, created_at: now, updated_at: now },
        { name: 'Iran', code: 'ir', flag_url: null, created_at: now, updated_at: now },
        { name: 'Iceland', code: 'is', flag_url: null, created_at: now, updated_at: now },
        { name: 'Italy', code: 'it', flag_url: null, created_at: now, updated_at: now },
        { name: 'Jersey', code: 'je', flag_url: null, created_at: now, updated_at: now },
        { name: 'Jamaica', code: 'jm', flag_url: null, created_at: now, updated_at: now },
        { name: 'Jordan', code: 'jo', flag_url: null, created_at: now, updated_at: now },
        { name: 'Japan', code: 'jp', flag_url: null, created_at: now, updated_at: now },
        { name: 'Kenya', code: 'ke', flag_url: null, created_at: now, updated_at: now },
        { name: 'Kyrgyzstan', code: 'kg', flag_url: null, created_at: now, updated_at: now },
        { name: 'Cambodia', code: 'kh', flag_url: null, created_at: now, updated_at: now },
        { name: 'Kiribati', code: 'ki', flag_url: null, created_at: now, updated_at: now },
        { name: 'Comoros', code: 'km', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Saint Kitts and Nevis',
          code: 'kn',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'North Korea', code: 'kp', flag_url: null, created_at: now, updated_at: now },
        { name: 'South Korea', code: 'kr', flag_url: null, created_at: now, updated_at: now },
        { name: 'Kuwait', code: 'kw', flag_url: null, created_at: now, updated_at: now },
        { name: 'Cayman Islands', code: 'ky', flag_url: null, created_at: now, updated_at: now },
        { name: 'Kazakhstan', code: 'kz', flag_url: null, created_at: now, updated_at: now },
        { name: 'Laos', code: 'la', flag_url: null, created_at: now, updated_at: now },
        { name: 'Lebanon', code: 'lb', flag_url: null, created_at: now, updated_at: now },
        { name: 'Saint Lucia', code: 'lc', flag_url: null, created_at: now, updated_at: now },
        { name: 'Liechtenstein', code: 'li', flag_url: null, created_at: now, updated_at: now },
        { name: 'Sri Lanka', code: 'lk', flag_url: null, created_at: now, updated_at: now },
        { name: 'Liberia', code: 'lr', flag_url: null, created_at: now, updated_at: now },
        { name: 'Lesotho', code: 'ls', flag_url: null, created_at: now, updated_at: now },
        { name: 'Lithuania', code: 'lt', flag_url: null, created_at: now, updated_at: now },
        { name: 'Luxembourg', code: 'lu', flag_url: null, created_at: now, updated_at: now },
        { name: 'Latvia', code: 'lv', flag_url: null, created_at: now, updated_at: now },
        { name: 'Libya', code: 'ly', flag_url: null, created_at: now, updated_at: now },
        { name: 'Morocco', code: 'ma', flag_url: null, created_at: now, updated_at: now },
        { name: 'Monaco', code: 'mc', flag_url: null, created_at: now, updated_at: now },
        { name: 'Moldova', code: 'md', flag_url: null, created_at: now, updated_at: now },
        { name: 'Montenegro', code: 'me', flag_url: null, created_at: now, updated_at: now },
        { name: 'Madagascar', code: 'mg', flag_url: null, created_at: now, updated_at: now },
        { name: 'Marshall Islands', code: 'mh', flag_url: null, created_at: now, updated_at: now },
        { name: 'Macedonia [FYROM]', code: 'mk', flag_url: null, created_at: now, updated_at: now },
        { name: 'Mali', code: 'ml', flag_url: null, created_at: now, updated_at: now },
        { name: 'Myanmar [Burma]', code: 'mm', flag_url: null, created_at: now, updated_at: now },
        { name: 'Mongolia', code: 'mn', flag_url: null, created_at: now, updated_at: now },
        { name: 'Macau', code: 'mo', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Northern Mariana Islands',
          code: 'mp',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Martinique', code: 'mq', flag_url: null, created_at: now, updated_at: now },
        { name: 'Mauritania', code: 'mr', flag_url: null, created_at: now, updated_at: now },
        { name: 'Montserrat', code: 'ms', flag_url: null, created_at: now, updated_at: now },
        { name: 'Malta', code: 'mt', flag_url: null, created_at: now, updated_at: now },
        { name: 'Mauritius', code: 'mu', flag_url: null, created_at: now, updated_at: now },
        { name: 'Maldives', code: 'mv', flag_url: null, created_at: now, updated_at: now },
        { name: 'Malawi', code: 'mw', flag_url: null, created_at: now, updated_at: now },
        { name: 'Mexico', code: 'mx', flag_url: null, created_at: now, updated_at: now },
        { name: 'Malaysia', code: 'my', flag_url: null, created_at: now, updated_at: now },
        { name: 'Mozambique', code: 'mz', flag_url: null, created_at: now, updated_at: now },
        { name: 'Namibia', code: 'na', flag_url: null, created_at: now, updated_at: now },
        { name: 'New Caledonia', code: 'nc', flag_url: null, created_at: now, updated_at: now },
        { name: 'Niger', code: 'ne', flag_url: null, created_at: now, updated_at: now },
        { name: 'Norfolk Island', code: 'nf', flag_url: null, created_at: now, updated_at: now },
        { name: 'Nigeria', code: 'ng', flag_url: null, created_at: now, updated_at: now },
        { name: 'Nicaragua', code: 'ni', flag_url: null, created_at: now, updated_at: now },
        { name: 'Netherlands', code: 'nl', flag_url: null, created_at: now, updated_at: now },
        { name: 'Norway', code: 'no', flag_url: null, created_at: now, updated_at: now },
        { name: 'Nepal', code: 'np', flag_url: null, created_at: now, updated_at: now },
        { name: 'Nauru', code: 'nr', flag_url: null, created_at: now, updated_at: now },
        { name: 'Niue', code: 'nu', flag_url: null, created_at: now, updated_at: now },
        { name: 'New Zealand', code: 'nz', flag_url: null, created_at: now, updated_at: now },
        { name: 'Oman', code: 'om', flag_url: null, created_at: now, updated_at: now },
        { name: 'Panama', code: 'pa', flag_url: null, created_at: now, updated_at: now },
        { name: 'Peru', code: 'pe', flag_url: null, created_at: now, updated_at: now },
        { name: 'French Polynesia', code: 'pf', flag_url: null, created_at: now, updated_at: now },
        { name: 'Papua New Guinea', code: 'pg', flag_url: null, created_at: now, updated_at: now },
        { name: 'Philippines', code: 'ph', flag_url: null, created_at: now, updated_at: now },
        { name: 'Pakistan', code: 'pk', flag_url: null, created_at: now, updated_at: now },
        { name: 'Poland', code: 'pl', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Saint Pierre and Miquelon',
          code: 'pm',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Pitcairn Islands', code: 'pn', flag_url: null, created_at: now, updated_at: now },
        { name: 'Puerto Rico', code: 'pr', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Palestinian Territories',
          code: 'ps',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Portugal', code: 'pt', flag_url: null, created_at: now, updated_at: now },
        { name: 'Palau', code: 'pw', flag_url: null, created_at: now, updated_at: now },
        { name: 'Paraguay', code: 'py', flag_url: null, created_at: now, updated_at: now },
        { name: 'Qatar', code: 'qa', flag_url: null, created_at: now, updated_at: now },
        { name: 'Réunion', code: 're', flag_url: null, created_at: now, updated_at: now },
        { name: 'Romania', code: 'ro', flag_url: null, created_at: now, updated_at: now },
        { name: 'Serbia', code: 'rs', flag_url: null, created_at: now, updated_at: now },
        { name: 'Russia', code: 'ru', flag_url: null, created_at: now, updated_at: now },
        { name: 'Rwanda', code: 'rw', flag_url: null, created_at: now, updated_at: now },
        { name: 'Saudi Arabia', code: 'sa', flag_url: null, created_at: now, updated_at: now },
        { name: 'Solomon Islands', code: 'sb', flag_url: null, created_at: now, updated_at: now },
        { name: 'Seychelles', code: 'sc', flag_url: null, created_at: now, updated_at: now },
        { name: 'Sudan', code: 'sd', flag_url: null, created_at: now, updated_at: now },
        { name: 'Sweden', code: 'se', flag_url: null, created_at: now, updated_at: now },
        { name: 'Singapore', code: 'sg', flag_url: null, created_at: now, updated_at: now },
        { name: 'Saint Helena', code: 'sh', flag_url: null, created_at: now, updated_at: now },
        { name: 'Slovenia', code: 'si', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Svalbard and Jan Mayen',
          code: 'sj',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Slovakia', code: 'sk', flag_url: null, created_at: now, updated_at: now },
        { name: 'Sierra Leone', code: 'sl', flag_url: null, created_at: now, updated_at: now },
        { name: 'San Marino', code: 'sm', flag_url: null, created_at: now, updated_at: now },
        { name: 'Senegal', code: 'sn', flag_url: null, created_at: now, updated_at: now },
        { name: 'Somalia', code: 'so', flag_url: null, created_at: now, updated_at: now },
        { name: 'Suriname', code: 'sr', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'São Tomé and Príncipe',
          code: 'st',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'El Salvador', code: 'sv', flag_url: null, created_at: now, updated_at: now },
        { name: 'Syria', code: 'sy', flag_url: null, created_at: now, updated_at: now },
        { name: 'Swaziland', code: 'sz', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Turks and Caicos Islands',
          code: 'tc',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Chad', code: 'td', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'French Southern Territories',
          code: 'tf',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Togo', code: 'tg', flag_url: null, created_at: now, updated_at: now },
        { name: 'Thailand', code: 'th', flag_url: null, created_at: now, updated_at: now },
        { name: 'Tajikistan', code: 'tj', flag_url: null, created_at: now, updated_at: now },
        { name: 'Tokelau', code: 'tk', flag_url: null, created_at: now, updated_at: now },
        { name: 'Timor-Leste', code: 'tl', flag_url: null, created_at: now, updated_at: now },
        { name: 'Turkmenistan', code: 'tm', flag_url: null, created_at: now, updated_at: now },
        { name: 'Tunisia', code: 'tn', flag_url: null, created_at: now, updated_at: now },
        { name: 'Tonga', code: 'to', flag_url: null, created_at: now, updated_at: now },
        { name: 'Turkey', code: 'tr', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Trinidad and Tobago',
          code: 'tt',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Tuvalu', code: 'tv', flag_url: null, created_at: now, updated_at: now },
        { name: 'Taiwan', code: 'tw', flag_url: null, created_at: now, updated_at: now },
        { name: 'Tanzania', code: 'tz', flag_url: null, created_at: now, updated_at: now },
        { name: 'Ukraine', code: 'ua', flag_url: null, created_at: now, updated_at: now },
        { name: 'Uganda', code: 'ug', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'U.S. Minor Outlying Islands',
          code: 'um',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'United States', code: 'us', flag_url: null, created_at: now, updated_at: now },
        { name: 'Uruguay', code: 'uy', flag_url: null, created_at: now, updated_at: now },
        { name: 'Uzbekistan', code: 'uz', flag_url: null, created_at: now, updated_at: now },
        { name: 'Vatican City', code: 'va', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'Saint Vincent and the Grenadines',
          code: 'vc',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Venezuela', code: 've', flag_url: null, created_at: now, updated_at: now },
        {
          name: 'British Virgin Islands',
          code: 'vg',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        {
          name: 'U.S. Virgin Islands',
          code: 'vi',
          flag_url: null,
          created_at: now,
          updated_at: now,
        },
        { name: 'Vietnam', code: 'vn', flag_url: null, created_at: now, updated_at: now },
        { name: 'Vanuatu', code: 'vu', flag_url: null, created_at: now, updated_at: now },
        { name: 'Wallis and Futuna', code: 'wf', flag_url: null, created_at: now, updated_at: now },
        { name: 'Samoa', code: 'ws', flag_url: null, created_at: now, updated_at: now },
        { name: 'Kosovo', code: 'xk', flag_url: null, created_at: now, updated_at: now },
        { name: 'Yemen', code: 'ye', flag_url: null, created_at: now, updated_at: now },
        { name: 'Mayotte', code: 'yt', flag_url: null, created_at: now, updated_at: now },
        { name: 'South Africa', code: 'za', flag_url: null, created_at: now, updated_at: now },
        { name: 'Zambia', code: 'zm', flag_url: null, created_at: now, updated_at: now },
        { name: 'Zimbabwe', code: 'zw', flag_url: null, created_at: now, updated_at: now },
      ])
    })
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}
